tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "universal-ctags/universal-ctags"
brew "libffi"
brew "git"
brew "global"
brew "openssl"
brew "lua"
brew "rbenv"
brew "the_silver_searcher"
brew "zsh"
brew "zsh-completions"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
